### ISSUE TITLE
PostgreSQL 9.2: unrecognized configuration parameter "unix_socket_directories" 

### ISSUE THREAD

**Issue by dpursehouse** [kbrebanov/ansible-postgresql#1]
Is 9.2 supported? I'm getting this error:

```
TASK: [kbrebanov.postgresql | Ensure PostgreSQL is started and enabled on boot] *** 
failed: [myhostname] => {"failed": true}
msg:  * Starting PostgreSQL 9.2 database server
 * The PostgreSQL server failed to start. Please check the log output:
LOG:  unrecognized configuration parameter "unix_socket_directories" in file "/etc/postgresql/9.2/main/postgresql.conf" line 68
FATAL:  configuration file "/etc/postgresql/9.2/main/postgresql.conf" contains errors
   ...fail!


FATAL: all hosts have already failed -- aborting
```

**Comment by kbrebanov** [comment]
@dpursehouse That parameter was named "unix_socket_directory" in <= 9.2. It got renamed to "unix_socket_directories" in 9.3.

I have not tested this role with <= 9.2 so there may be other configuration parameters that have changed.

This role also uses the PGDG apt repo and it only provides 9.3 & 9.4. How are you getting it to install 9.2?

**Comment by dpursehouse** [comment]
> This role also uses the PGDG apt repo and it only provides 9.3 & 9.4. How are you getting it to install 9.2?

9.2 is available in the default repository on my distribution (Ubuntu 14.04 with a private corporate repo) so I added a new task to prevent it from adding the PGDG repo, similar to the PR that I sent on ansible-java.

That wasn't enough, though.  I also had to do this to make it recognize the package names:

```
diff --git a/vars/Ubuntu.yml b/vars/Ubuntu.yml
index 1e599d3..ffb6191 100644
--- a/vars/Ubuntu.yml
+++ b/vars/Ubuntu.yml
@@ -2,7 +2,6 @@
 # vars file for postgresql (Ubuntu specific)

 postgresql_packages:
-  - postgresql={{ postgresql_version }}*
-  - libpq-dev={{ postgresql_version }}*
-  - python-psycopg2
+  - postgresql-{{ postgresql_version }}
+  - postgresql-common
```

I haven't sent these changes as a PR because I wasn't sure if 9.2 was supported.  I'll try with 9.3, but I have a feeling I'll still need to fix the package names.

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
